/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rog
 */
public class pro extends javax.swing.JPanel {

    /**
     * @return the mod
     */
    public static DefaultTableModel getMod() {
        return mod;
    }

    /**
     * @param aMod the mod to set
     */
    public static void setMod(DefaultTableModel aMod) {
        mod = aMod;
    }

    /**
     * @return the id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the price
     */
    public double getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(double price) {
        DecimalFormat df=new DecimalFormat("$ #,##0.00");
        this.price = price;
        lbprice.setText("Price : "+df.format(price));
    }

    /**
     * @return the qty
     */
    public int getQty() {
        return qty;
    }

    /**
     * @param qty the qty to set
     */
    public void setQty(int qty) {
        this.qty = qty;
    }

    /**
     * @return the pic
     */
    public Icon getPic() {
        return pic;
    }

    /**
     * @param pic the pic to set
     */
    public void setPic(Icon pic) {
        this.pic = pic;
        lbimage.setIcon(pic);
    }

    /**
     * @return the lprice
     */
    public String getLprice() {
        return lprice;
    }

    /**
     * @param lprice the lprice to set
     */
    public void setLprice(String lprice) {
        this.lprice = lprice;
        lbprice.setText("Price : "+lprice);
    }

    /**
     * @return the pprice
     */
   

    /**
     * @return the pname
     */
    public String getPname() {
        return pname;
    }

    /**
     * @param pname the pname to set
     */
    public void setPname(String pname) {
        this.pname = pname;
        
        txtproname.setText("Product Name : "+pname);
    }

    /**
     * @return the pname
     */
   

    /**
     * @param pname the pname to set
     */
   

    /**
     * Creates new form pro
     */
    public pro() {
        initComponents();
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbimage = new javax.swing.JLabel();
        txtproname = new javax.swing.JTextField();
        lbprice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbimage.setBackground(new java.awt.Color(0, 0, 0));
        lbimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/image/images.png"))); // NOI18N
        lbimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbimage.setName(""); // NOI18N

        txtproname.setBackground(new java.awt.Color(204, 204, 255));
        txtproname.setFont(new java.awt.Font("Khmer OS Battambang", 0, 18)); // NOI18N
        txtproname.setText("Product Name  : ");
        txtproname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtproname.setFocusable(false);
        txtproname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpronameActionPerformed(evt);
            }
        });

        lbprice.setBackground(new java.awt.Color(153, 204, 0));
        lbprice.setFont(new java.awt.Font("Khmer OS Battambang", 0, 18)); // NOI18N
        lbprice.setText("Price :");

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Khmer OS Battambang", 0, 12)); // NOI18N
        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Khmer OS Battambang", 0, 12)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setFont(new java.awt.Font("Khmer OS Battambang", 0, 12)); // NOI18N
        jButton3.setText("Buy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtproname)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbprice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(lbimage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbimage, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtproname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbprice))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtpronameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpronameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpronameActionPerformed
    private int findindexbyid(String id){
        for(int i=0;i<mod.getRowCount();i++){
            String idorder=""+mod.getValueAt(i, 0);
            if(id.equals(idorder)){
                return i;
            }
            
        }
        return -1;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(this,pname+"  "+lprice);
    qty++;
        if(qty==1){
            String [] row={id,pname,""+price+"$",""+qty,""+price+"$"};
            mod.addRow(row);
        }
        else{
            int index=findindexbyid(id);
//            double total= Double.parseDouble(lprice)*qty; covert form string to double
            double total= price*qty;
            mod.setValueAt(qty, index, 3);
            mod.setValueAt(total+"$", index, 4);
            
            
        }
         
        jButton1.setText("Buy("+qty+")");
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton3.setText("Total : "+(qty*price)+"$");
//        for(int i=0;i<mod.getRowCount();i++){
//            String id=""+mod.getValueAt(i,0);
//            if(id.equals(this.id)){
//                mod.removeRow(i);
//                qty++;
//            }
//        }
        
        
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        qty--;
        int index=findindexbyid(id);
//        for(int i=0;i<mod.getRowCount();i++){
//            String id=""+mod.getValueAt(i, 0);
//            if(id.equals(this.id)){
//                mod.removeRow(i);
//            }
//        }
         jButton3.setText("Total : "+(qty*price)+"$");
        if(qty==0){
            mod.removeRow(index);
            jButton1.setText("Buy");
            jButton2.setVisible(false);
            jButton3.setVisible(false);
            
            
            
            
        }else {
            mod.setValueAt(qty, index, 3);
            mod.setValueAt(qty*price+"$", index, 4);
            jButton1.setText("Buy("+qty+")");
            
            
            
           
            
          
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private String pname;
    private String lprice;
    private Icon pic;
    private int qty;
    private double price;
    private String id;
    private static DefaultTableModel mod=new DefaultTableModel(new String[]{"ID","Pro_Name","U_pric","Qty","Total"},0);
            
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lbimage;
    private javax.swing.JLabel lbprice;
    private javax.swing.JTextField txtproname;
    // End of variables declaration//GEN-END:variables
}
