/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.GridBagConstraints;
import java.awt.Insets;

import java.io.File;
import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author Rog
 */
public class SellHero extends javax.swing.JFrame {

    /**
     * Creates new form SellHero
     */
    public SellHero() {
        initComponents();
        File f= new File("C:\\Users\\Rog\\OneDrive\\Pictures\\c++\\im\\people");
        File []list = f.listFiles();
        GridBagConstraints gbc=new GridBagConstraints();
        int x=0,y=0;
        Random r= new Random();
//        DecimalFormat df=new DecimalFormat("$#.##0,00");
        for(int i=0;i<list.length;i++){
            pro hero=new pro();
            hero.setPname(list[i].getName().substring(0, list[i].getName().length()-4));
            hero.setPic(new ImageIcon(list[i].getAbsolutePath()));
            int p=r.nextInt(10)+1;
            hero.setPrice(p);
            hero.setId(""+(i+1));
            
            
            
            
            gbc.insets=new Insets(20, 20, 20, 20);
            gbc.gridx=x;
            gbc.gridy=y;
            HeroPanel.add(hero,gbc);
            x++;
            if(x==2){
                x=0;
                y++;
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HeroPanel = new javax.swing.JPanel();
        showhero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeroPanel.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(HeroPanel);

        showhero.setText("Show Hero");
        showhero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showheroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(489, 489, 489)
                .addComponent(showhero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(510, 510, 510))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(showhero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showheroActionPerformed
        // TODO add your handling code here:
        ShowInformationaboutSell n=new ShowInformationaboutSell(this, true);
        n.setVisible(true);
        
    }//GEN-LAST:event_showheroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellHero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellHero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellHero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellHero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellHero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeroPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showhero;
    // End of variables declaration//GEN-END:variables
}
